# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1113, 688)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(30, 50, 481, 591))
        self.tableWidget.setAccessibleName("")
        self.tableWidget.setAutoScrollMargin(16)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./images/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        item.setIcon(icon)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./images/one.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        item.setIcon(icon1)
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./images/scissor.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        item.setIcon(icon2)
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./images/six.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        item.setIcon(icon3)
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./images/good.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        item.setIcon(icon4)
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("./images/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        item.setIcon(icon5)
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("./images/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        item.setIcon(icon6)
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("./images/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        item.setIcon(icon7)
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("./images/clockwise.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        item.setIcon(icon8)
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("./images/clockwise-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        item.setIcon(icon9)
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(38)
        self.tableWidget.verticalHeader().setDefaultSectionSize(90)
        self.tableWidget.verticalHeader().setMinimumSectionSize(35)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 60, 91, 21))
        self.label.setMouseTracking(False)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setScaledContents(False)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "Close"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "One"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "Scissor"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "Six"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "Good"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "Down"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Form", "Open"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Form", "OK"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Form", "Clockwise"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Form", "Clockwise-left"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "滑鼠模式"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "鍵盤模式"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", "雙擊右鍵"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Form", "右鍵，快轉5秒"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Form", "操控游標"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Form", "開啟動態操作"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Form", "滑鼠右鍵"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("Form", "播放/暫停"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Form", "靜止1秒，切換模式"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("Form", "滑鼠滾輪向前"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("Form", "音量增加5%"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("Form", "滑鼠滾輪向後"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("Form", "音量減少5%"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("Form", "none"))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("Form", "左鍵，倒退5秒"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("Form", "回上頁"))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("Form", "開啟CC字幕"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("Form", "動態操作：調快影片速度0.25倍"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("Form", "動態操作：調慢影片速度0.25倍"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Form", "手勢動作"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())


